import type {
  AppSettings,
  Category,
  LunchRunSession,
  Order,
  OrderItem,
  PendingProductMatch,
  PriceHistoryEntry,
  PriceImportLog,
  Product,
  Store,
} from "@/lib/types";
import { DEFAULT_SETTINGS } from "@/lib/constants";

const now = new Date();
const today = now.toISOString().slice(0, 10);
const thisMorning = new Date(now);
thisMorning.setHours(8, 4, 0, 0);

export const DEMO_STORES: Store[] = [
  {
    id: "store-dg",
    name: "Dollar General",
    address: "Near campus",
    active: true,
    is_default: true,
    price_source: "Dollar General Online",
    external_location_id: "DG-LOCAL",
    hours: "8:00 AM – 10:00 PM",
  },
  {
    id: "store-sng",
    name: "Stop-N-Go",
    address: "Main Street",
    active: true,
    is_default: false,
    price_source: "Manual",
    external_location_id: null,
    hours: "6:00 AM – 11:00 PM",
  },
];

export const DEMO_CATEGORIES: Category[] = [
  { id: "cat-drinks", name: "Drinks", slug: "drinks", icon: "CupSoda", sort_order: 1, shopping_order: 1, active: true },
  { id: "cat-energy", name: "Energy Drinks", slug: "energy-drinks", icon: "Zap", sort_order: 2, shopping_order: 2, active: true },
  { id: "cat-chips", name: "Chips", slug: "chips", icon: "Cookie", sort_order: 3, shopping_order: 3, active: true },
  { id: "cat-candy", name: "Candy", slug: "candy", icon: "Candy", sort_order: 4, shopping_order: 4, active: true },
  { id: "cat-jerky", name: "Jerky", slug: "jerky", icon: "Beef", sort_order: 5, shopping_order: 5, active: true },
  { id: "cat-snacks", name: "Snacks", slug: "snacks", icon: "Popcorn", sort_order: 6, shopping_order: 6, active: true },
  { id: "cat-gum", name: "Gum", slug: "gum", icon: "CircleDot", sort_order: 7, shopping_order: 7, active: true },
  { id: "cat-other", name: "Other", slug: "other", icon: "Package", sort_order: 8, shopping_order: 8, active: true },
];

function product(
  partial: Omit<Product, "created_at" | "updated_at" | "archived" | "active"> &
    Partial<Pick<Product, "archived" | "active">>,
): Product {
  return {
    active: true,
    archived: false,
    created_at: thisMorning.toISOString(),
    updated_at: thisMorning.toISOString(),
    ...partial,
  };
}

export const DEMO_PRODUCTS: Product[] = [
  product({
    id: "p-monster-ultra",
    name: "Monster Energy Ultra White",
    brand: "Monster",
    description: "Zero sugar energy drink",
    size: "16 oz",
    flavor: "Ultra White",
    category_id: "cat-energy",
    image_url: null,
    store_id: "store-dg",
    current_price: 2.85,
    min_price: 2.5,
    max_price: 3.5,
    popularity: 98,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-monster-ultra-white",
    max_quantity: 4,
  }),
  product({
    id: "p-monster-orig",
    name: "Monster Energy Original",
    brand: "Monster",
    description: "Classic green Monster",
    size: "16 oz",
    flavor: "Original",
    category_id: "cat-energy",
    image_url: null,
    store_id: "store-dg",
    current_price: 2.85,
    min_price: 2.5,
    max_price: 3.5,
    popularity: 90,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-monster-original",
    max_quantity: 4,
  }),
  product({
    id: "p-redbull",
    name: "Red Bull",
    brand: "Red Bull",
    description: "Energy drink",
    size: "8.4 oz",
    flavor: "Original",
    category_id: "cat-energy",
    image_url: null,
    store_id: "store-dg",
    current_price: 2.75,
    min_price: 2.25,
    max_price: 3.25,
    popularity: 85,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-redbull",
    max_quantity: 4,
  }),
  product({
    id: "p-drpepper",
    name: "Dr Pepper",
    brand: "Dr Pepper",
    description: "Soda",
    size: "20 oz",
    flavor: "Original",
    category_id: "cat-drinks",
    image_url: null,
    store_id: "store-dg",
    current_price: 1.75,
    min_price: 1.5,
    max_price: 2.25,
    popularity: 80,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-drpepper-20",
    max_quantity: 4,
  }),
  product({
    id: "p-coke",
    name: "Coca-Cola",
    brand: "Coca-Cola",
    description: "Classic cola",
    size: "20 oz",
    flavor: "Original",
    category_id: "cat-drinks",
    image_url: null,
    store_id: "store-dg",
    current_price: 1.75,
    min_price: 1.5,
    max_price: 2.25,
    popularity: 78,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-coke-20",
    max_quantity: 4,
  }),
  product({
    id: "p-gatorade",
    name: "Gatorade",
    brand: "Gatorade",
    description: "Sports drink",
    size: "20 oz",
    flavor: "Fruit Punch",
    category_id: "cat-drinks",
    image_url: null,
    store_id: "store-dg",
    current_price: 1.85,
    min_price: 1.5,
    max_price: 2.5,
    popularity: 70,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-gatorade",
    max_quantity: 4,
  }),
  product({
    id: "p-takis",
    name: "Takis Fuego",
    brand: "Takis",
    description: "Hot chili pepper tortilla chips",
    size: "9.9 oz",
    flavor: "Fuego",
    category_id: "cat-chips",
    image_url: null,
    store_id: "store-dg",
    current_price: 3.25,
    min_price: 2.5,
    max_price: 4.0,
    popularity: 95,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-takis-fuego",
    max_quantity: 3,
  }),
  product({
    id: "p-doritos",
    name: "Doritos Nacho Cheese",
    brand: "Doritos",
    description: "Tortilla chips",
    size: "9.25 oz",
    flavor: "Nacho Cheese",
    category_id: "cat-chips",
    image_url: null,
    store_id: "store-dg",
    current_price: 3.15,
    min_price: 2.5,
    max_price: 3.75,
    popularity: 75,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-doritos-nacho",
    max_quantity: 3,
  }),
  product({
    id: "p-cheetos",
    name: "Cheetos Flamin' Hot",
    brand: "Cheetos",
    description: "Flamin' Hot cheese snacks",
    size: "8.5 oz",
    flavor: "Flamin' Hot",
    category_id: "cat-chips",
    image_url: null,
    store_id: "store-dg",
    current_price: 3.15,
    min_price: 2.5,
    max_price: 3.75,
    popularity: 88,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-cheetos-fh",
    max_quantity: 3,
  }),
  product({
    id: "p-reeses",
    name: "Reese's Peanut Butter Cups",
    brand: "Reese's",
    description: "Chocolate peanut butter cups",
    size: "1.5 oz",
    flavor: "Milk Chocolate",
    category_id: "cat-candy",
    image_url: null,
    store_id: "store-dg",
    current_price: 1.45,
    min_price: 1.0,
    max_price: 2.0,
    popularity: 82,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-reeses",
    max_quantity: 5,
  }),
  product({
    id: "p-sourpatch",
    name: "Sour Patch Kids",
    brand: "Sour Patch",
    description: "Sour then sweet candy",
    size: "8 oz",
    flavor: "Original",
    category_id: "cat-candy",
    image_url: null,
    store_id: "store-dg",
    current_price: 2.95,
    min_price: 2.25,
    max_price: 3.5,
    popularity: 72,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-sourpatch",
    max_quantity: 3,
  }),
  product({
    id: "p-skittles",
    name: "Skittles",
    brand: "Skittles",
    description: "Fruit candy",
    size: "7 oz",
    flavor: "Original",
    category_id: "cat-candy",
    image_url: null,
    store_id: "store-dg",
    current_price: 2.85,
    min_price: 2.25,
    max_price: 3.5,
    popularity: 68,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-skittles",
    max_quantity: 3,
  }),
  product({
    id: "p-jack-orig",
    name: "Jack Link's Original Beef Jerky",
    brand: "Jack Link's",
    description: "Beef jerky",
    size: "3.25 oz",
    flavor: "Original",
    category_id: "cat-jerky",
    image_url: null,
    store_id: "store-dg",
    current_price: 5.49,
    min_price: 4.5,
    max_price: 6.5,
    popularity: 77,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-jack-original",
    max_quantity: 2,
  }),
  product({
    id: "p-jack-teri",
    name: "Jack Link's Teriyaki Beef Jerky",
    brand: "Jack Link's",
    description: "Teriyaki beef jerky",
    size: "3.25 oz",
    flavor: "Teriyaki",
    category_id: "cat-jerky",
    image_url: null,
    store_id: "store-dg",
    current_price: 5.49,
    min_price: 4.5,
    max_price: 6.5,
    popularity: 84,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-jack-teriyaki",
    max_quantity: 2,
  }),
  product({
    id: "p-slimjim",
    name: "Slim Jim",
    brand: "Slim Jim",
    description: "Meat stick",
    size: "Giant",
    flavor: "Original",
    category_id: "cat-jerky",
    image_url: null,
    store_id: "store-dg",
    current_price: 1.65,
    min_price: 1.25,
    max_price: 2.0,
    popularity: 65,
    available: true,
    last_price_update: thisMorning.toISOString(),
    external_product_url: null,
    external_product_id: "dg-slimjim",
    max_quantity: 5,
  }),
];

export const DEMO_SESSION: LunchRunSession = {
  id: "session-today",
  date: today,
  store_id: "store-dg",
  open_time: "07:00",
  cutoff_time: "11:30",
  delivery_window: "Lunch period",
  status: "open",
  max_orders: 20,
  created_at: thisMorning.toISOString(),
};

function makeItem(
  id: string,
  orderId: string,
  overrides: Partial<OrderItem> & Pick<OrderItem, "product_name" | "quantity" | "max_price">,
): OrderItem {
  return {
    id,
    order_id: orderId,
    product_id: null,
    is_custom: false,
    brand: null,
    size: null,
    flavor: null,
    description: null,
    estimated_price: null,
    min_estimated: null,
    max_estimated: null,
    actual_price: null,
    tax_amount: 0,
    substitution: "closest_under_max",
    substitution_notes: null,
    status: "pending",
    replacement_name: null,
    replacement_price: null,
    picked_up: false,
    image_url: null,
    ...overrides,
  };
}

const tylerItems: OrderItem[] = [
  makeItem("oi-t1", "ord-tyler", {
    product_id: "p-monster-ultra",
    product_name: "Monster Energy Ultra White",
    brand: "Monster",
    size: "16 oz",
    flavor: "Ultra White",
    quantity: 1,
    estimated_price: 2.85,
    min_estimated: 2.5,
    max_estimated: 3.5,
    max_price: 3.5,
  }),
  makeItem("oi-t2", "ord-tyler", {
    product_id: "p-jack-teri",
    product_name: "Jack Link's Teriyaki Beef Jerky",
    brand: "Jack Link's",
    size: "3.25 oz",
    flavor: "Teriyaki",
    quantity: 1,
    estimated_price: 5.49,
    min_estimated: 4.5,
    max_estimated: 6.5,
    max_price: 6.0,
  }),
];

const emmaItems: OrderItem[] = [
  makeItem("oi-e1", "ord-emma", {
    product_id: "p-drpepper",
    product_name: "Dr Pepper",
    brand: "Dr Pepper",
    size: "20 oz",
    quantity: 1,
    estimated_price: 1.75,
    min_estimated: 1.5,
    max_estimated: 2.25,
    max_price: 2.25,
  }),
  makeItem("oi-e2", "ord-emma", {
    product_id: "p-takis",
    product_name: "Takis Fuego",
    brand: "Takis",
    size: "9.9 oz",
    flavor: "Fuego",
    quantity: 1,
    estimated_price: 3.25,
    min_estimated: 2.5,
    max_estimated: 4.0,
    max_price: 4.0,
  }),
  makeItem("oi-e3", "ord-emma", {
    product_id: "p-reeses",
    product_name: "Reese's Peanut Butter Cups",
    brand: "Reese's",
    size: "1.5 oz",
    quantity: 1,
    estimated_price: 1.45,
    min_estimated: 1.0,
    max_estimated: 2.0,
    max_price: 2.0,
  }),
];

const jakeItems: OrderItem[] = [
  makeItem("oi-j1", "ord-jake", {
    product_id: "p-redbull",
    product_name: "Red Bull",
    brand: "Red Bull",
    size: "8.4 oz",
    quantity: 2,
    estimated_price: 2.75,
    min_estimated: 2.25,
    max_estimated: 3.25,
    max_price: 3.25,
  }),
];

function orderBase(
  partial: Omit<Order, "updated_at" | "delivered_at" | "tax_amount" | "tip_amount" | "change_owed" | "amount_paid" | "merchandise_actual" | "final_total" | "delivery_location_other"> &
    Partial<Order>,
): Order {
  return {
    tip_amount: 0,
    tax_amount: 0,
    merchandise_actual: null,
    final_total: null,
    amount_paid: 0,
    change_owed: 0,
    delivery_location_other: null,
    delivered_at: null,
    updated_at: thisMorning.toISOString(),
    ...partial,
  };
}

export const DEMO_ORDERS: Order[] = [
  orderBase({
    id: "ord-tyler",
    order_code: "LR-1047",
    tracking_token: "demo-token-tyler-m-1047",
    session_id: "session-today",
    customer_name: "Tyler M.",
    delivery_location: "Cafeteria",
    payment_method: "Cash Prepay",
    notes: "Blue hoodie",
    status: "received",
    payment_status: "paid",
    merchandise_estimate_min: 8.0,
    merchandise_estimate_max: 10.0,
    service_fee: 1.5,
    estimated_total_min: 9.5,
    estimated_total_max: 11.5,
    max_authorized_total: 11.0,
    amount_paid: 12.0,
    created_at: new Date(thisMorning.getTime() + 30 * 60000).toISOString(),
    items: tylerItems,
  }),
  orderBase({
    id: "ord-emma",
    order_code: "LR-1048",
    tracking_token: "demo-token-emma-r-1048",
    session_id: "session-today",
    customer_name: "Emma R.",
    delivery_location: "Commons",
    payment_method: "Cash Prepay",
    notes: null,
    status: "received",
    payment_status: "unpaid",
    merchandise_estimate_min: 6.0,
    merchandise_estimate_max: 8.25,
    service_fee: 1.5,
    estimated_total_min: 7.5,
    estimated_total_max: 9.75,
    max_authorized_total: 9.75,
    created_at: new Date(thisMorning.getTime() + 45 * 60000).toISOString(),
    items: emmaItems,
  }),
  orderBase({
    id: "ord-jake",
    order_code: "LR-1049",
    tracking_token: "demo-token-jake-s-1049",
    session_id: "session-today",
    customer_name: "Jake S.",
    delivery_location: "Hallway",
    payment_method: "Cash Prepay",
    notes: null,
    status: "received",
    payment_status: "paid",
    merchandise_estimate_min: 4.5,
    merchandise_estimate_max: 6.5,
    service_fee: 1.5,
    estimated_total_min: 6.0,
    estimated_total_max: 8.0,
    max_authorized_total: 8.0,
    amount_paid: 8.0,
    created_at: new Date(thisMorning.getTime() + 60 * 60000).toISOString(),
    items: jakeItems,
  }),
];

export const DEMO_PRICE_HISTORY: PriceHistoryEntry[] = DEMO_PRODUCTS.map((p, i) => ({
  id: `ph-${i}`,
  product_id: p.id,
  old_price: p.current_price ? roundish(p.current_price - 0.1) : null,
  new_price: p.current_price ?? 0,
  store_id: p.store_id,
  source: "seed",
  created_at: thisMorning.toISOString(),
}));

function roundish(n: number) {
  return Math.round(n * 100) / 100;
}

export const DEMO_SETTINGS: AppSettings = { ...DEFAULT_SETTINGS };

export const DEMO_IMPORT_LOGS: PriceImportLog[] = [];
export const DEMO_PENDING_MATCHES: PendingProductMatch[] = [];
